services:
  app:
    &services-app
    build:
      context: .
      target: development
    init: true
    networks:
      default:
        aliases:
          - app.test
    volumes:
      - ./:/opt/app
    ports:
      - 3000:3000
  shell:
    build:
      context: .
      target: development
    init: true
    working_dir: /opt/app
    volumes:
      - ./:/opt/app
    entrypoint: []
