services:
  app:
    build: !reset
    image: ${DOCKER_APP_IMAGE}
    environment: !override
      - LDAP_HOST=ldap.fake.edu
      - LDAP_PASS=FAKEPW
    entrypoint: ["tail", "-f", "/dev/null"] 
    volumes: !override
      - artifacts:/opt/app/artifacts

volumes:
  artifacts:

