attributes:
  - berkeleyeduexpdate
  - berkeleyeduhcmid
  - berkeleyeduaffid
  - berkeleyeduaffiliations
  - berkeleyedubirthday
  - berkeleyedubirthmonth
  - berkeleyedubirthyear
  - berkeleyedualternateid
  - berkeleyeducsid
  - berkeleyeduemptitlecode
  - berkeleyeduempdeptunittitlecode
  - berkeleyedukerberosprincipalstring
  - berkeleyedustuid
  - employeenumber
  - employeetype
  - uid
  - berkeleyeduunithrdeptname
  - givenname
  - sn
  - berkeleyeduofficialemail
  - berkeleyeduprimarydeptunit
  - postaladdress
  - postalcode
  - telephonenumber
  - mail

student_affiliation:
  - "STUDENT-TYPE-REGISTERED"
  - "STUDENT-TYPE-NOT REGISTERED"
  - "FORMER-STUDENT-IN-GRACE"
