ucpath:
  root: <%= ENV['UCPATH_API_URL'] || 'https://apis.berkeley.edu/uat/hr/v3/' %>
  id: <%= ENV['UCPATH_API_ID'] || '4de5e867' %>
  key: <%= ENV['UCPATH_API_KEY'] || 'MISSING' %>

sis:
  root: <%= ENV['SIS_API_URL'] || 'MISSING' %>
  id: <%= ENV['SIS_API_ID'] || 'MISSING' %>
  key: <%= ENV['SIS_API_KEY'] || 'MISSING' %>

alma:
  url: <%= ENV['ALMA_API_URL'] || 'https://apis.berkeley.edu/uat/hr/v3/' %>
  key: <%= ENV['ALMA_API_KEY'] || 'MISSING' %>

ldap:
  host: <%= ENV['LDAP_HOST'] || 'MISSING' %>
  pass: <%= ENV['LDAP_PASS'] || 'MISSING' %>
