ucpath:
  root: <%= ENV['UCPATH_API_URL'] || 'https://apis.berkeley.edu/uat/hr/v3/' %>
  id: <%= ENV['UCPATH_API_ID'] || '4de5e867' %>
  key: <%= ENV['UCPATH_API_KEY'] || 'MISSING' %>

sis:
  root: <%= ENV['SIS_API_URL'] || 'https://apis.berkeley.edu/sis/v2/students' %>
  id: <%= ENV['SIS_API_ID'] || 'a6ee93d7' %>
  key: <%= ENV['SIS_API_KEY'] || 'MISSING' %>

ldap:
  host: <%= ENV['LDAP_HOST'] || 'ldap.berkeley.edu' %>
  pass: <%= ENV['LDAP_PASS'] || 'MISSING' %>
