library_staff_job_code:
  - "000118"
  - "000541"
  - "000542"
  - "000543"
  - "003600"
  - "003610"
  - "003612"
  - "003613"
  - "003614"
  - "003615"
  - "003616"
  - "003617"
  - "003618"
  - "003619"
  - "003620"
  - "003621"
  - "003622"
  - "003623"
  - "003635"
  - "003637"
  - "003639"
  - "006268"
  - "006286"
  - "006287"
  - "006757"
  - "006758"
  - "006759"
  - "006760"
  - "006761"
  - "006762"
  - "006765"
  - "006766"
  - "006767"
  - "006772"
  - "006773"
  - "006776"
  - "004445"

postdoc_job_code:
  - "003252"
  - "003253"
  - "003254"

visiting_scholar_job_code:
  - "CWR003"
  - "CWR015"
  - "CWR016"

ucb_academic_dept_affiliate_code:
  - "CWR022"

emeritus_job_code:
  - "001132"
  - "001620"
  - "001621"
  - "003249"
  - "003800"
  - "009902"

# Users with these job codes are NOT eligible and are skipped
# AP-402: Added codes
# AP-576 & AP-590: Added some student job codes and renamed list
exclude_job_code:
  - "CWR005"
  - "CWR006"
  - "CWR011"
  - "CWR017"
  - "CWR002"
  - "CWR014"
  - "CWR019"
  - "CWR021"
  - "002320"
  - "003282"
  - "004919"
  - "002851"

library_staff_dept_code_prefix:
  - "KPADM"
  - "KSBAN"

academic_classification_indic:
  - "A"

executive_classification_indic:
  - "2"
  - "3"

uc_extension_faculty:
  - "EXADM"
  - "HYACD"

# These jobs will always be considered "eligible" regardless
# of any student affiliations
priority_job_codes:
  - "006761"

# The 0FTE (percent of full time employment) excludes these
# job codes
fte_check_exclusions:
  - "CWR022"
  - "CWR015"
  - "CWR003"
  - "CWR016"
  - "001550"
