employee:
  tablename: employees
  fields:
    - name: ucpath_employee_id
      jpath: '$..identifiers[?(@.type=="hr-employee-id")].id'
      status: REQUIRED

    - name: legacy_employee_id
      jpath: '$..identifiers[?(@.type=="legacy-hr-employee-id")].id'
      status: OPTIONAL

    - name: uid
      jpath: '$..identifiers[?(@.type=="campus-uid")].id'
      status: OPTIONAL

    - name: first_name
      jpath: '$..names[?(@.type.code=="PRF")].givenName'
      status: PREFERRED

    - name: middle_name
      jpath: '$..names[?(@.type.code=="PRF")].middleName'
      status: OPTIONAL

    - name: last_name
      jpath: '$..names[?(@.type.code=="PRF")].familyName'
      status: PREFERRED

    - name: suffix_name
      jpath: '$..names[?(@.type.code=="PRF")].suffixName'
      status: OPTIONAL

    - name: formatted_name
      jpath: '$..names[?(@.type.code=="PRF")].formattedName'
      status: OPTIONAL

    - name: name_type
      jpath: '$..names[?(@.type.code=="PRF")].type.code'
      status: OPTIONAL

    - name: email
      jpath: "$..emails[?(@.primary==true)].emailAddress"
      status: OPTIONAL

    - name: email_primary_code
      jpath: "$..emails[?(@.primary==true)].primary"
      status: OPTIONAL

    - name: email_type
      jpath: "$..emails[?(@.primary==true)].type.code"
      status: OPTIONAL

    - name: phone_number
      jpath: "$..phones[?(@.primary==true)].number"
      alt_jpath: "$..phones[0].number"
      status: OPTIONAL

    - name: phone_primary_code
      jpath: "$..phones[?(@.primary==true)].primary"
      dbdef: "VARCHAR(16)"
      status: OPTIONAL

    - name: phone_type
      jpath: "$..phones[?(@.primary==true)].type.code"
      status: OPTIONAL

    - name: pref_name_givenname
      jpath: '$..names[?(@.type.code=="PRF")].givenName'
      status: PREFERRED

    - name: pref_name_middlename
      jpath: '$..names[?(@.type.code=="PRF")].middleName'
      status: OPTIONAL

    - name: pref_name_familyname
      jpath: '$..names[?(@.type.code=="PRF")].familyName'
      status: PREFERRED

    - name: db_date_added

    - name: db_date_modified

job:
  fields:
    - name: job_code
      jpath: "$.position.jobCode.code.code"
      dbdef: "VARCHAR(16)"
      status: OPTIONAL

    - name: dept_code
      jpath: "$.department.code"
      dbdef: "VARCHAR(16)"
      status: OPTIONAL

    - name: dept_desc
      jpath: "$.department.description"
      dbdef: "VARCHAR(64)"
      status: OPTIONAL

    - name: location_code
      jpath: "$.location.code"
      dbdef: "VARCHAR(32)"
      status: OPTIONAL

    - name: location_description
      jpath: "$.location.description"
      dbdef: "VARCHAR(128)"
      status: OPTIONAL

    - name: primary_code
      jpath: "$.primary.code"
      dbdef: "VARCHAR(8)"
      status: OPTIONAL

    - name: empl_type_code
      jpath: "$.type.code"
      dbdef: "VARCHAR(16)"
      status: OPTIONAL

    - name: job_status_code
      jpath: "$.position.jobCode.status.code"
      dbdef: "VARCHAR(8)"
      status: OPTIONAL

    - name: position_status_code
      jpath: "$.position.status.code"
      dbdef: "VARCHAR(8)"
      status: OPTIONAL

    - name: position_number
      jpath: "$.position.number"
      dbdef: "VARCHAR(8)"
      status: OPTIONAL

    - name: hr_status_code
      jpath: "$.status.hrStatus.code"
      dbdef: "VARCHAR(8)"
      status: OPTIONAL

    - name: emp_status_code
      jpath: "$.status.employmentStatus.code"
      dbdef: "VARCHAR(8)"
      status: OPTIONAL

    - name: org_relationship_code
      jpath: "$.organizationRelationship.code"
      dbdef: "VARCHAR(16)"
      status: OPTIONAL

    - name: last_action_code
      jpath: "$.actions.lastAction.code"
      dbdef: "VARCHAR(16)"
      status: OPTIONAL

    - name: appointment_end_date
      jpath: "$.actions.assignmentEndDate"
      dbdef: "VARCHAR(16)"
      status: OPTIONAL

    - name: classification_indc
      jpath: "$.classification.code"
      dbdef: "VARCHAR(16)"
      status: OPTIONAL

    - name: org_node_deptid
      jpath: "$.department.code"
      dbdef: "VARCHAR(16)"
      status: OPTIONAL

    - name: expected_end_date
      jpath: "$.actions.expectedEndDate"
      dbdef: "VARCHAR(16)"
      status: OPTIONAL

    - name: intial_hire_date
      jpath: "$.actions.initialHireDate"
      dbdef: "VARCHAR(16)"
      status: OPTIONAL

    - name: initial_assignment_start_date
      jpath: "$.actions.initialAssignmentStartDate"
      dbdef: "VARCHAR(16)"
      status: OPTIONAL

    - name: job_assigned_date
      jpath: "$.actions.jobAssignedDate"
      dbdef: "VARCHAR(16)"
      status: OPTIONAL

    - name: dept_assigned_date
      jpath: "$.actions.departmentAssignedDate"
      dbdef: "VARCHAR(16)"
      status: OPTIONAL

    - name: expected_return_date
      jpath: "$.actions.expectedReturnDate"
      dbdef: "VARCHAR(16)"
      status: OPTIONAL

    - name: termination_date
      jpath: "$.actions.terminationDate"
      dbdef: "VARCHAR(16)"
      status: OPTIONAL

    - name: percent_of_fulltime
      jpath: "$.position.percentOfFullTime"
      dbdef: "VARCHAR(16)"
      status: OPTIONAL
